apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: tgr
  labels:
    app: redis-server
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-nfs-pvc
  namespace: tgr
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: tgr
  labels:
    app: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      volumes:
      - name: redis-nfs
        persistentVolumeClaim:
          claimName: redis-nfs-pvc
      containers:
      - name: redis
        image: cragginstylie/tgr.redis:arm64-v1.0
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 6379
          protocol: TCP
        volumeMounts:
        - name: redis-nfs
          mountPath: /data
